config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  get 'enquiries', to: 'enquiries#index'
  get 'enquiries/new'
  post 'enquiries', to: 'enquiries#create'
=======
  get 'enquiries', to: "enquiries#index"
  get 'enquiries/new'
  post 'enquiries', to: "enquiries#create"
  
>>>>>>> 45a365c924b14b7993ce0a846a35426a4ae21e2e
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do
    resources :reviews
  end
  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books, dependent: :destroy

    def full_name
        "#{first_name} #{last_name}"
    end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :reviews, dependent: :destroy
  has_many :book_genres, dependent: :destroy
  has_many :genres, through: :book_genres
end

app/models/book_genre.rb
class BookGenre < ApplicationRecord
  belongs_to :book
  belongs_to :genre
end

app/models/enquiry.rb
class Enquiry < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :book_genres, dependent: :destroy
  has_many :books, through: :book_genres
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :edit, :update]

  def index
    @books = Book.all
  end

  def show
  end

  # Display the form
  def new
    @book = Book.new
  end

  def create
    Book.create(book_params)
    redirect_to root_path
  end

  def edit
  end

  def update
    @book.update(book_params)
    redirect_to @book
  end

  private

  def find_book
    @book = Book.find(params[:id])
  end

  def book_params
    return params.require(:book).permit(:title, :pub_year, :author_id)
  end
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
<<<<<<< HEAD
=======
  def index
    @enquiries = Enquiry.all
  end

>>>>>>> 45a365c924b14b7993ce0a846a35426a4ae21e2e
  def new
    @enquiry = Enquiry.new
  end

  def create
<<<<<<< HEAD
    enquiry = Enquiry.create(enquiry_params)
    render plain: params
  end

  def index
    @enquiries = Enquiry.all
  end

  private 
  def enquiry_params
    params.require(:enquiry).permit(:name, :email, :phone, :message)
  end    
  
=======
    @enquiry = Enquiry.create(enquiry_params)
  end

  private

  def enquiry_params
    params.require(:enquiry).permit(:name, :email, :phone, :message)
  end
>>>>>>> 45a365c924b14b7993ce0a846a35426a4ae21e2e
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/views/books/_form.html.erb
<%= form_with model: book, local: true do |f| %>
<div>
  <%= f.label :title %> <%= f.text_field :title %>
</div>
<div>
  <%= f.label :pub_year %> <%= f.text_field :pub_year %>
</div>
<div>
  <%= f.label :author %>
  <%#
    collection_select(model, foreign_key, foreign collection, primary key, label)
  %>
  <%= collection_select(:book, :author_id, Author.all, :id, :full_name) %>
</div>
<div>
  <%= f.submit %>
</div>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render "form", book: @book %>

app/views/books/index.html.erb
<h1>Books</h1>

<h3><%= link_to "New Book", new_book_path %></h3>

<ul>
    <% @books.each do |book| %>
        <li>
            <h2><%= link_to book.title, book_path(book) %></h2>
            <h4>By <%= book.author.first_name.capitalize %> <%= book.author.last_name.capitalize %></h4>
            <h6><%= book.pub_year %></h6>
        </li>
    <% end %>
</ul>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render "form", book: @book %>

app/views/books/show.html.erb
<h2><%= @book.title %></h2>
<h4>By <%= @book.author.first_name.capitalize %> <%= @book.author.last_name.capitalize %></h4>
<h6><%= @book.pub_year %></h6>
<hr>
<% if !@book.reviews.empty? %>
    <h1>Reviews</h1>
    <ul>
        <% @book.reviews.each do |review| %>
            <p>Rating: <%= review.rating %></p>
            <p>Date: <%= review.date %></p>
            <p><%= review.comment %></p>
        <% end %>
    </ul>
<% end %>
<%= link_to "Edit Book", edit_book_path(@book) %>

app/views/enquiries/create.html.erb
<h1>Thanks for your enquiry!</h1>

<p>You entered the following details:</p>
<p>
    <dt>Name</dt>
    <dd><%= @enquiry.name %></dd>
</p>
<p>
    <dt>Email</dt>
    <dd><%= @enquiry.email %></dd>
</p>
<p>
    <dt>Phone</dt>
    <dd><%= @enquiry.phone %></dd>
</p>
<p>
    <dt>Message</dt>
    <dd><%= @enquiry.message %></dd>
</p>

app/views/enquiries/index.html.erb
<<<<<<< HEAD
<h1>All Enquiries</h1>

<% @enquiries.each do |data| %>
    <h3><%= data.name %></h3>
    <h5>E: <%= data.email %> P: <%= data.email %><h5>
    <p> Message: <%= data.message %></p>
<% end %>
=======
<h1>All Enquiries (<%= @enquiries.count %>)</h1>

<% @enquiries.each do |enquiry| %>
    <h3><%= enquiry.name %></h3>
    <h5>E: <%= enquiry.email %>   P: <%= enquiry.phone %></h5>
    <p><%= enquiry.message %></p>
    <hr>
<% end %>
>>>>>>> 45a365c924b14b7993ce0a846a35426a4ae21e2e

app/views/enquiries/new.html.erb
<h1>New Enquiry</h1>

<%= form_with model: @enquiry, local: true do |f| %>
<<<<<<< HEAD
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.label :email %>
        <%= f.email_field :email %>
    </div>
    <div>
        <%= f.label :phone %>
        <%= f.telephone_field :phone %>
    </div>
    <div>
        <%= f.label :message %>
        <%= f.text_area :message %>
    </div>
    <div>
        <%= f.submit %>
    </div>
=======
<div>
  <%= f.label :name %> <%= f.text_field :name %>
</div>
<div>
  <%= f.label :email %> <%= f.email_field :email %>
</div>
<div>
  <%= f.label :phone %> <%= f.telephone_field :phone %>
</div>
<div>
    <%= f.label :message %> <%= f.text_area :message %>
</div>
<div>
  <%= f.submit %>
</div>
>>>>>>> 45a365c924b14b7993ce0a846a35426a4ae21e2e
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookclub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <header>
  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "New Book", new_book_path %></li>
      <li><%= link_to "New Enquiry", enquiries_new_path %></li>
      <li><%= link_to "Enquiries List", enquiries_path %></li>
    </ul>
  </nav>
  </header>
    <%= yield %>
  </body>
</html>